import AppKit

// MARK: - 剪贴板监听（轮询 changeCount）

final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    /// 默认忽略密码管理器内容（功能清单 1.7），设置页可关
    var ignorePasswordManagers: Bool = UserDefaults.standard.object(forKey: "ignorePassword") as? Bool ?? true {
        didSet { UserDefaults.standard.set(ignorePasswordManagers, forKey: "ignorePassword") }
    }

    var onText: ((String) -> Void)?
    var onImage: ((NSImage) -> Void)?

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount

    private init() {}

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
        timer?.tolerance = 0.1
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if ignorePasswordManagers, isPrivate(pb) { return }

        if let s = pb.string(forType: .string), !s.isEmpty {
            onText?(s)
        } else if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff),
                  let img = NSImage(data: data) {
            onImage?(img)
        }
    }

    /// 密码管理器隐私标记（1Password 等兼容）
    private func isPrivate(_ pb: NSPasteboard) -> Bool {
        let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        let types = pb.types ?? []
        return types.contains(concealed) || types.contains(transient) || types.contains(autoGenerated)
    }
}
