import AppKit

// MARK: - 剪贴板监听（轮询 changeCount）

final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    /// 默认忽略密码管理器内容（功能清单 1.7），设置页可关
    var ignorePasswordManagers: Bool = UserDefaults.standard.object(forKey: "ignorePassword") as? Bool ?? true {
        didSet { UserDefaults.standard.set(ignorePasswordManagers, forKey: "ignorePassword") }
    }

    var onText: ((String) -> Void)?
    var onImage: ((NSImage) -> Void)?
    /// 优先通道：剪贴板自带 PNG 字节时直通存储（免 NSImage 解码 + 免二次 PNG 编码）
    var onImageData: ((Data) -> Void)?
    /// Finder ⌘C 复制的文件（fileURL 类型）
    var onFile: ((String) -> Void)?

    /// 应用自身即将写剪贴板时调用：下一次变更不计入历史
    /// （显式 addImage 已入册，监听再收会造成重复；风险窗口 ≤0.5s，期间用户复制会被跳过，可接受）
    private var pendingSelfWrites = 0
    func suppressNextCapture() { pendingSelfWrites += 1 }

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount

    private init() {}

    func start() {
        guard timer == nil else { return }
        // 0.3s 轮询：0.5s 时连续快速复制会丢中间那次（复制 A 后立刻复制 B → A 永远不入册）
        timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: true) { [weak self] _ in
            self?.poll()
        }
        timer?.tolerance = 0.05
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        if pendingSelfWrites > 0 {
            pendingSelfWrites -= 1
            return
        }

        if ignorePasswordManagers, isPrivate(pb) { return }

        // 文件复制（Finder 等）：先看类型表里有没有 fileURL 再读对象（无文件时零开销）；
        // 纯 legacy alias 类型（部分脚本写入）暂不支持，Finder 路径恒有 fileURL
        if pb.types?.contains(.fileURL) == true,
           let urls = pb.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           let url = urls.first, url.isFileURL, FileManager.default.fileExists(atPath: url.path) {
            onFile?(url.path)
            return
        }

        if let s = pb.string(forType: .string), !s.isEmpty {
            onText?(s)
        } else if let png = pb.data(forType: .png) {
            onImageData?(png)
        } else if let tiff = pb.data(forType: .tiff), let img = NSImage(data: tiff) {
            // TIFF 来源才需要 NSImage 解码；编码成 PNG 的开销在存储层后台队列完成
            onImage?(img)
        }
    }

    /// 密码管理器隐私标记（1Password 等兼容）
    private func isPrivate(_ pb: NSPasteboard) -> Bool {
        let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        let types = pb.types ?? []
        return types.contains(concealed) || types.contains(transient) || types.contains(autoGenerated)
    }
}
